image: maven:3.6.3-openjdk-17

variables:
  MVN_CMD: "mvn install -B"

cache:
  key: "$CI_COMMIT_REF_SLUG"


stages:
  - build
  - release

build:
  stage: build
  script:
    - cd Application
    - $MVN_CMD
  artifacts:
    paths:
      - "Application/target/Application-1.0-SNAPSHOT.jar"
    expire_in: 1 week  # Set how long to keep artifacts
    
release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - echo "running release_job"
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
